[versions]
kotlin = "2.2.21"
spockk = "0.1.0"

[libraries]
spockk-core = { module = "io.github.pshevche.spockk:spockk-core", version.ref = "spockk" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version = "6.0.1" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-power-assert = { id = "org.jetbrains.kotlin.plugin.power-assert", version.ref = "kotlin" }
spockk = { id = "io.github.pshevche.spockk", version.ref = "spockk" }
